version: "3.5"

services:
# Left for example:
#  stream-overlay:
#    depends_on:
#      - backend-nginx
#      - radio-manager-backend
#      - radio-streamer
#    networks:
#      - myownradio-dev
#    image: node:18
#    command: npm start
#    working_dir: /code
#    volumes:
#      - ./services/stream-overlay:/code
#    user: "${USER}"
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.overlay.rule=PathPrefix(`/stream-overlay`)
#      - traefik.http.services.overlay.loadbalancer.server.port=3000
  traefik:
    depends_on:
      - backend-nginx
    networks:
      - myownradio-dev
    image: library/traefik:2.4
    ports:
      - "127.0.0.1:40180:80"
      - "127.0.0.1:40181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
  db:
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40001:3306"
  redis:
    image: redis:alpine3.18
    volumes:
      - redis-data:/data
    networks:
      - myownradio-dev
  backend-nginx:
    depends_on:
      - backend-php-fpm
    image: myownradio/backend-nginx-base:1.0.2
    volumes:
      - ./services/backend:/code:ro
    networks:
      - myownradio-dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/`)
      - traefik.http.routers.backend.middlewares=corsBackend
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.middlewares.corsBackend.headers.accesscontrolallowmethods=GET,POST
      - traefik.http.middlewares.corsBackend.headers.accesscontrolallowheaders=authorization
      - traefik.http.middlewares.corsBackend.headers.accesscontrolalloworiginlist=http://localhost:3000
      - traefik.http.middlewares.corsBackend.headers.accesscontrolallowcredentials=true
  backend-php-fpm:
    depends_on:
      - db
      - file-server
    image: myownradio/backend-php-base:3.0.6
    working_dir: /code
    volumes:
      - ./services/backend:/code:rw
    user: "${USER}"
    networks:
      - myownradio-dev
    environment:
      COMPOSER_HOME: /code/.cache/composer-home
  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./images/migration/Dockerfile
    networks:
      - myownradio-dev
    environment:
      MYSQL_DB: "mor"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "db"
  file-server:
    image: myownradio/file-server:1.0.2
    volumes:
      - ./services/backend/.cache/storage:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:40004:80"
    networks:
      - myownradio-dev
  radio-streamer:
    depends_on:
      - radio-manager-backend
      - file-server
    build:
      context: ./services/radio-streamer
      dockerfile: Dockerfile
    user: "${USER}"
    working_dir: /code
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40003:8080"
    env_file:
      - services/radio-streamer/.env
  radiomanager-pubsub-backend:
    depends_on:
      - redis
    build:
      context: services/radiomanager-pubsub-backend
      dockerfile: Dockerfile
    user: "${USER}"
    working_dir: /code
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40006:8080"
    env_file:
      - services/radiomanager-pubsub-backend/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.pubsub.rule=Path(`/pubsub/channel/{channelId:[a-z]+}/subscribe`)
      - traefik.http.routers.pubsub.middlewares=stripprefixPubsub,forwardauthPubsub,corsPubsub
      - traefik.http.services.pubsub.loadbalancer.server.port=8080
      - traefik.http.middlewares.stripprefixPubsub.stripprefix.prefixes=/pubsub
      - traefik.http.middlewares.forwardauthPubsub.forwardauth.address=http://radio-manager-backend:8080/v0/forward-auth/by-token
      - traefik.http.middlewares.forwardauthPubsub.forwardauth.authResponseHeaders=user-id
      - traefik.http.middlewares.forwardauthPubsub.forwardauth.trustForwardHeader=false
      - traefik.http.middlewares.corsPubsub.headers.accesscontrolallowmethods=GET
      - traefik.http.middlewares.corsPubsub.headers.accesscontrolallowheaders=authorization
      - traefik.http.middlewares.corsPubsub.headers.accesscontrolalloworiginlist=http://localhost:3000
      - traefik.http.middlewares.corsPubsub.headers.accesscontrolallowcredentials=true

  radio-manager-backend:
    depends_on:
      - radiomanager-web-egress-controller
    build:
      context: services/radio-manager-backend
      dockerfile: Dockerfile
    volumes:
      - ./services/backend/.cache/storage:/data:rw
    user: "${USER}"
    working_dir: /code
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40005:8080"
    env_file:
      - services/radio-manager-backend/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.radioManager.rule=PathPrefix(`/radio-manager/api/`)
      - traefik.http.routers.radioManager.middlewares=stripprefixRadioManager,forwardauthRadioManager,corsRadioManager
      - traefik.http.routers.radioManagerPub.rule=PathPrefix(`/radio-manager/api/pub`)
      - traefik.http.routers.radioManagerPub.middlewares=stripprefixRadioManager,corsRadioManager
      - traefik.http.services.radioManager.loadbalancer.server.port=8080
      - traefik.http.middlewares.stripprefixRadioManager.stripprefix.prefixes=/radio-manager/api
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.address=http://radio-manager-backend:8080/v0/forward-auth/by-token
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.authResponseHeaders=user-id
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.trustForwardHeader=false
      - traefik.http.middlewares.corsRadioManager.headers.accesscontrolallowmethods=GET,POST
      - traefik.http.middlewares.corsRadioManager.headers.accesscontrolallowheaders=authentication,content-type
      - traefik.http.middlewares.corsRadioManager.headers.accesscontrolalloworiginlist=http://localhost:3000
      - traefik.http.middlewares.corsRadioManager.headers.accesscontrolallowcredentials=true
  radiomanager-web-egress-controller:
    build:
      context: services/radiomanager-web-egress-controller
      dockerfile: Dockerfile
    volumes:
      - ./services/radiomanager-web-egress-controller/.kube:/.kube:ro
    user: "${USER}"
    working_dir: /code
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40007:8080"
    env_file:
      - services/radiomanager-web-egress-controller/.env
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  myownradio-dev:
    name: myownradio-dev

