[package]
name = "scheduler-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_millis = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json"] }
thiserror = { version = "2.0.12" }
